# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'

    - script: python -m pip install --upgrade pip setuptools wheel
      displayName: 'Install pip'

    - script: pip install SQFLint
      displayName: 'Install SQFLint'
    
    - script: python tools/sqf_validator.py
      displayName: 'SQF Validator'

    - script: python tools/config_style_checker.py
      displayName: 'Config style checker'

    - script: sqflint -d Mission/
      displayName: 'SQFLint'